#include "precomp_dboclient.h"
#include "PacketTracer.h"

// Core
#include "NtlDebug.h"

// Shared
#include "NtlPacketAU.h"
#include "NtlPacketCU.h"
#include "NtlPacketGU.h"
#include "NtlPacketTU.h"
#include "NtlPacketUA.h"
#include "NtlPacketUC.h"
#include "NtlPacketUG.h"
#include "NtlPacketUT.h"

// Simulation
#include "NtlSLDef.h"
#include "NtlSLGlobal.h"
#include "NtlSob.h"
#include "NtlSobAvatar.h"
#include "NtlSobManager.h"
#include "NtlSLEventFunc.h"
#include "NtlSLLogic.h"

// Client
#include "DumpCommand.h"
#include "DboGlobal.h"

#define	PACKETNAME_INSERT(name)		m_mapPacketName.insert(PacketEnumNameMap::value_type(name, #name))

CPacketTracer* CPacketTracer::m_pInstance = NULL;

CPacketTracer* CPacketTracer::GetInstance()
{
	return m_pInstance;
}

void CPacketTracer::CreateInstance()
{
#ifndef _ENABLE_PACKET_TRACE_
	return;
#endif

	if(NULL == m_pInstance)
	{
		m_pInstance = NTL_NEW CPacketTracer;
		m_pInstance->Create();
	}
}

void CPacketTracer::DeleteInstance()
{
#ifndef _ENABLE_PACKET_TRACE_
	return;
#endif
	if(m_pInstance)
	{
		m_pInstance->Destroy();
		NTL_DELETE(m_pInstance);
	}
}

CPacketTracer::CPacketTracer()
{
	m_bAvtivate = FALSE;
	m_eTraceMode = CAPTURE_ALL;
}

CPacketTracer::~CPacketTracer()
{

}

void CPacketTracer::SetRangeOpCode(int iMin, int iMax)
{
	m_iMinOpCode = iMin;
	if(-1 != iMax)
		m_iMaxOpCode = iMax;
}

void CPacketTracer::SetTraceMode(TRACE_MODE eTraceMode)
{
	m_eTraceMode = eTraceMode;
}

const char* CPacketTracer::GetPacketName(int iOpCode)
{
	PacketEnumNameMap::iterator iter = m_mapPacketName.find(iOpCode);

	if(m_mapPacketName.end() != iter)
	{
		return iter->second.c_str();
	}
	else
		return NULL;
}

void CPacketTracer::Activate()
{
	m_bAvtivate = TRUE;
}

void CPacketTracer::Deactivate()
{
	m_bAvtivate = FALSE;
}

void CPacketTracer::Process(sNTLPACKETHEADER* pPacket, RwBool bReceive)
{
	if(true == m_bAvtivate)
	{
		if(pPacket->wOpCode >= m_iMinOpCode && pPacket->wOpCode <= m_iMaxOpCode)
		{
			char pcFileNameTemp[150];
			char pcFileNameTemp2[300];
			/// Dump....
			const char* pcName = GetPacketName(pPacket->wOpCode);

			if(pcName)
				strncpy(pcFileNameTemp, pcName, 150);
			else
				sprintf_s(pcFileNameTemp, 150, "UnknownPacket: %d", pPacket->wOpCode);
			pcFileNameTemp[149] = NULL;

			if(true == bReceive)
				sprintf_s(pcFileNameTemp2, 300, "Receive: %s	%d\n", pcFileNameTemp, timeGetTime());
			else
				sprintf_s(pcFileNameTemp2, 300, "Send   : %s	%d\n", pcFileNameTemp, timeGetTime());

			pcFileNameTemp2[299] = NULL;

			GetDumpCmdManager()->OutputDump(pcFileNameTemp2);
		}
	}
}

VOID CPacketTracer::HandleEvents( RWS::CMsg& msg )
{
	if(msg.Id == g_EventNotifySendPacket && (CAPTURE_ALL == m_eTraceMode || CAPTURE_SEND == m_eTraceMode))
		Process((sNTLPACKETHEADER*) msg.pData, FALSE);
	else if(msg.Id == g_EventNotifyReceivePacket && (CAPTURE_ALL == m_eTraceMode || CAPTURE_RECEIVE == m_eTraceMode))
		Process((sNTLPACKETHEADER*) msg.pData, TRUE);
}

void CPacketTracer::Destroy()
{
	UnLinkMsg(g_EventNotifySendPacket);
	UnLinkMsg(g_EventNotifyReceivePacket);
}

void CPacketTracer::Create()
{
	LinkMsg(g_EventNotifySendPacket, 0);
	LinkMsg(g_EventNotifyReceivePacket, 0);

	SetRangeOpCode(0, 0x7fffffff);

#ifdef _ENABLE_PACKET_TRACE_	/// Protocol may change. Automatic build may fail
	m_mapPacketName.insert(PacketEnumNameMap::value_type(AU_LOGIN_RES, "AU_LOGIN_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(AU_LOGIN_DISCONNECT_RES, "AU_LOGIN_DISCONNECT_RES"));

	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_SERVER_FARM_INFO, "CU_SERVER_FARM_INFO"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_SERVER_CHANNEL_INFO, "CU_SERVER_CHANNEL_INFO"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_LOGIN_RES, "CU_LOGIN_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_SERVERLIST_RES, "CU_CHARACTER_SERVERLIST_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_SERVERLIST_ONE_RES, "CU_CHARACTER_SERVERLIST_ONE_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_ADD_RES, "CU_CHARACTER_ADD_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_DEL_RES, "CU_CHARACTER_DEL_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_SELECT_RES, "CU_CHARACTER_SELECT_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_INFO, "CU_CHARACTER_INFO"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_LOAD_RES, "CU_CHARACTER_LOAD_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_EXIT_RES, "CU_CHARACTER_EXIT_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_DEL_CANCEL_RES, "CU_CHARACTER_DEL_CANCEL_RES"));
	//m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_DEL_INFO, "CU_CHARACTER_DEL_INFO"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_DISCONNECTED_NFY, "CU_DISCONNECTED_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_SERVER_FARM_INFO_REFRESHED_NFY, "CU_SERVER_FARM_INFO_REFRESHED_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_SERVER_CHANNEL_INFO_REFRESHED_NFY, "CU_SERVER_CHANNEL_INFO_REFRESHED_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CONNECT_WAIT_CHECK_RES, "CU_CONNECT_WAIT_CHECK_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CONNECT_WAIT_COUNT_NFY, "CU_CONNECT_WAIT_COUNT_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CONNECT_WAIT_CANCEL_RES, "CU_CONNECT_WAIT_CANCEL_RES"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CONNECT_WAIT_CANCEL_NFY, "CU_CONNECT_WAIT_CANCEL_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_NETMARBLEMEMBERIP_NFY, "CU_NETMARBLEMEMBERIP_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_DEL_NFY, "CU_CHARACTER_DEL_NFY"));
	m_mapPacketName.insert(PacketEnumNameMap::value_type(CU_CHARACTER_RENAME_RES, "CU_CHARACTER_RENAME_RES"));

	PACKETNAME_INSERT(GU_PONG);
	PACKETNAME_INSERT(GU_SESSION_STATE_WRONG);
	PACKETNAME_INSERT(GU_CHAR_STATE_WRONG);
	PACKETNAME_INSERT(GU_GAME_ENTER_RES);
	PACKETNAME_INSERT(GU_GAME_LEAVE_RES);
	PACKETNAME_INSERT(GU_ENTER_WORLD_RES);
	PACKETNAME_INSERT(GU_ENTER_WORLD_COMPLETE);
	PACKETNAME_INSERT(GU_AUTH_KEY_FOR_COMMUNITY_SERVER_RES);
	PACKETNAME_INSERT(GU_AVATAR_CHAR_INFO);
	PACKETNAME_INSERT(GU_AVATAR_ITEM_INFO);
	PACKETNAME_INSERT(GU_AVATAR_SKILL_INFO);
	PACKETNAME_INSERT(GU_AVATAR_HTB_INFO);
	PACKETNAME_INSERT(GU_AVATAR_BUFF_INFO);
	PACKETNAME_INSERT(GU_AVATAR_WORLD_INFO);
	PACKETNAME_INSERT(GU_AVATAR_ZONE_INFO);
	PACKETNAME_INSERT(GU_AVATAR_QUEST_COMPLETE_INFO);
	PACKETNAME_INSERT(GU_AVATAR_QUEST_PROGRESS_INFO);
	PACKETNAME_INSERT(GU_AVATAR_QUEST_INVENTORY_INFO);
	PACKETNAME_INSERT(GU_AVATAR_INFO_END);
	PACKETNAME_INSERT(GU_AVATAR_ATTRIBUTE_UPDATE);
	PACKETNAME_INSERT(GU_OBJECT_CREATE);
	PACKETNAME_INSERT(GU_OBJECT_DESTROY);
	PACKETNAME_INSERT(GU_CHAR_MOVE);
	PACKETNAME_INSERT(GU_CHAR_DEST_MOVE);
	PACKETNAME_INSERT(GU_CHAR_CHANGE_HEADING);
	PACKETNAME_INSERT(GU_CHAR_CHANGE_JUMP_DIRECTION);
	PACKETNAME_INSERT(GU_CHAR_CHANGE_DIRECTION_ON_FLOATING);
	PACKETNAME_INSERT(GU_CHAR_FOLLOW_MOVE);
	PACKETNAME_INSERT(GU_CHAR_JUMP);
	PACKETNAME_INSERT(GU_CHAR_JUMP_END);
	PACKETNAME_INSERT(GU_CHAR_FIGHTMODE);
	PACKETNAME_INSERT(GU_CHAR_BLOCK_MODE_COOL_TIME_NFY);
	PACKETNAME_INSERT(GU_CHAR_CAMPING);
	PACKETNAME_INSERT(GU_CHAR_FAINT);
	PACKETNAME_INSERT(GU_CHAR_KNOCKDOWN);
	PACKETNAME_INSERT(GU_CHAR_SLIDING);
	PACKETNAME_INSERT(GU_CHAR_CONVERT_CLASS);
	PACKETNAME_INSERT(GU_AVATAR_ATTRIBUTE_UPDATE);
	PACKETNAME_INSERT(GU_CHAR_DIALOG);
	PACKETNAME_INSERT(GU_CHAR_DIRECT_PLAY);
	PACKETNAME_INSERT(GU_CHAR_DIRECT_PLAY_END);
	PACKETNAME_INSERT(GU_CHAR_AWAY_RES);
	PACKETNAME_INSERT(GU_CHAR_MAIL_INFO);
	PACKETNAME_INSERT(GU_CHAR_KEY_INFO);
	PACKETNAME_INSERT(GU_CHAR_RANKBATTLE_SCORE);
	PACKETNAME_INSERT(GU_CHAR_KEY_UPDATE_RES);
	PACKETNAME_INSERT(GU_CHAR_ACTION_ATTACK);
	PACKETNAME_INSERT(GU_CHAR_ACTION_SKILL);
	PACKETNAME_INSERT(GU_CHAR_ACTION_ITEM);
	PACKETNAME_INSERT(GU_CHAR_REVIVAL_RES);
	PACKETNAME_INSERT(GU_CHAR_TELEPORT_RES);
	PACKETNAME_INSERT(GU_CHAR_BIND_RES);
	PACKETNAME_INSERT(GU_CHAR_SERVER_CHANGE_RES);
	PACKETNAME_INSERT(GU_CHAR_CHANNEL_CHANGE_RES);
	PACKETNAME_INSERT(GU_CHAR_EXIT_RES);
	PACKETNAME_INSERT(GU_CHAR_SKILL_RES);
	PACKETNAME_INSERT(GU_GAME_EXIT_RES);
	PACKETNAME_INSERT(GU_GAME_KICK_NFY);
	PACKETNAME_INSERT(GU_EFFECT_AFFECTED);
	PACKETNAME_INSERT(GU_SKILL_CASTING_CANCELED_NFY);
	PACKETNAME_INSERT(GU_SKILL_CASTING_DELAYED_NFY);
	PACKETNAME_INSERT(GU_SKILL_AFFECTING_CANCELED_NFY);
	PACKETNAME_INSERT(GU_SKILL_TARGET_LIST_REQ);
	PACKETNAME_INSERT(GU_SKILL_LEARN_RES);
	PACKETNAME_INSERT(GU_SKILL_LEARNED_NFY);
	PACKETNAME_INSERT(GU_SKILL_UPGRADE_RES);
	PACKETNAME_INSERT(GU_SKILL_RP_BONUS_SETTING_RES);
	PACKETNAME_INSERT(GU_SKILL_NOTIFY_EXP);
	PACKETNAME_INSERT(GU_SKILL_AFTEREFFECT_REMAINING_TIME_NFY);
	PACKETNAME_INSERT(GU_SKILL_COOL_TIME_STARTED_NFY);
	PACKETNAME_INSERT(GU_HTB_START_RES);
	PACKETNAME_INSERT(GU_HTB_LEARN_RES);
	PACKETNAME_INSERT(GU_HTB_FORWARD_RES);
	PACKETNAME_INSERT(GU_HTB_RP_BALL_USE_RES);
	PACKETNAME_INSERT(GU_HTB_RP_BALL_USED_NFY);
	PACKETNAME_INSERT(GU_HTB_RP_BALL_RESULT_DECIDED_NFY);
	PACKETNAME_INSERT(GU_BUFF_REGISTERED);
	PACKETNAME_INSERT(GU_BUFF_DROPPED);
	PACKETNAME_INSERT(GU_BUFF_REFRESH_ALL);
	PACKETNAME_INSERT(GU_BUFF_DROP_RES);
	PACKETNAME_INSERT(GU_ITEM_CREATE);
	PACKETNAME_INSERT(GU_ITEM_UPDATE);
	PACKETNAME_INSERT(GU_ITEM_MOVE_RES);
	PACKETNAME_INSERT(GU_ITEM_MOVE_STACK_RES);
	PACKETNAME_INSERT(GU_ITEM_DELETE);
	PACKETNAME_INSERT(GU_ITEM_DELETE_RES);
	PACKETNAME_INSERT(GU_ITEM_EQUIP_REPAIR_RES);			// Repair completion response
	PACKETNAME_INSERT(GU_ITEM_REPAIR_RES);
	PACKETNAME_INSERT(GU_ITEM_USE_RES); // Result of request to use item
	PACKETNAME_INSERT(GU_ITEM_CASTING_CANCELED);		// Notification that item casting has been cancelled.
	PACKETNAME_INSERT(GU_ITEM_CASTING_DELAYED_NFY);					// Notification that item casting has been delayed
	PACKETNAME_INSERT(GU_ITEM_DUR_DOWN);
	PACKETNAME_INSERT(GU_ITEM_DUR_UPDATE);
	PACKETNAME_INSERT(GU_ITEM_STACK_UPDATE);
	PACKETNAME_INSERT(GU_ITEM_UPGRADE_RES);
	PACKETNAME_INSERT(GU_ITEM_IDENTIFY_RES);
	PACKETNAME_INSERT(GU_ITEM_PICK_RES);
	PACKETNAME_INSERT(GU_ZENNY_PICK_RES);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_STATE);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_ASPECT_STATE);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_CONDITION);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_EXP);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_LEVEL);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_SPEED);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_ATTACK_SPEEDRATE);
	PACKETNAME_INSERT(GU_UPDATE_ITEM_EQUIP);	// It is only sent to neighbor PCs.
	PACKETNAME_INSERT(GU_UPDATE_ITEM_DELETED);	// 
	PACKETNAME_INSERT(GU_UPDATE_CHAR_LP);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_EP);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_RP);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_LP_EP);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_ZENNY);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_MUDOSA_POINT);
	PACKETNAME_INSERT(GU_SYSTEM_DISPLAY_TEXT); // text display
	PACKETNAME_INSERT(GU_SYSTEM_DISPLAY_RESULTCODE);	// ResultCode text is output to the client.
	PACKETNAME_INSERT(GU_SHOP_START_RES);
	PACKETNAME_INSERT(GU_SHOP_BUY_RES);
	PACKETNAME_INSERT(GU_SHOP_SELL_RES);
	PACKETNAME_INSERT(GU_SHOP_END_RES);
	PACKETNAME_INSERT(GU_PARTY_CREATE_RES);
	PACKETNAME_INSERT(GU_PARTY_DISBAND_RES);
	PACKETNAME_INSERT(GU_PARTY_DISBANDED_NFY);
	PACKETNAME_INSERT(GU_PARTY_INVITE_RES);
	PACKETNAME_INSERT(GU_PARTY_INVITE_NFY);
	PACKETNAME_INSERT(GU_PARTY_RESPONSE_INVITATION_RES);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_JOINED_NFY);
	PACKETNAME_INSERT(GU_PARTY_INFO);
	PACKETNAME_INSERT(GU_PARTY_INVITATION_DECLINED_NFY);
	PACKETNAME_INSERT(GU_PARTY_INVITATION_EXPIRED_NFY);
	PACKETNAME_INSERT(GU_PARTY_LEAVE_RES);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_LEFT_NFY);
	PACKETNAME_INSERT(GU_PARTY_KICK_OUT_RES);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_KICKED_OUT_NFY);
	PACKETNAME_INSERT(GU_PARTY_CHANGE_LEADER_RES);
	PACKETNAME_INSERT(GU_PARTY_LEADER_CHANGED_NFY);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_LEVELED_UP_NFY);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_CLASS_CHANGED_NFY);
	PACKETNAME_INSERT(GU_PARTY_CHANGE_ZENNY_LOOTING_METHOD_RES);
	PACKETNAME_INSERT(GU_PARTY_ZENNY_LOOTING_METHOD_CHANGED_NFY);
	PACKETNAME_INSERT(GU_PARTY_CHANGE_ITEM_LOOTING_METHOD_RES);
	PACKETNAME_INSERT(GU_PARTY_ITEM_LOOTING_METHOD_CHANGED_NFY);
	PACKETNAME_INSERT(GU_PARTY_ZENNY_LOOTING_METHOD_UNLOCKED_NFY);
	PACKETNAME_INSERT(GU_PARTY_ITEM_LOOTING_METHOD_UNLOCKED_NFY);
	PACKETNAME_INSERT(GU_PARTY_ZENNY_UPDATED_NFY);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_GAINED_ITEM_NFY);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_GAINED_ZENNY_NFY);
	PACKETNAME_INSERT(GU_PARTY_MEMBER_LOCATION_NFY);
	PACKETNAME_INSERT(GU_BANK_START_RES);
	PACKETNAME_INSERT(GU_BANK_MOVE_RES);
	PACKETNAME_INSERT(GU_BANK_MOVE_STACK_RES);
	PACKETNAME_INSERT(GU_BANK_END_RES);
	PACKETNAME_INSERT(GU_BANK_ZENNY_INFO);
	PACKETNAME_INSERT(GU_BANK_ITEM_INFO);
	PACKETNAME_INSERT(GU_BANK_ZENNY_RES);
	PACKETNAME_INSERT(GU_BANK_BUY_RES);
	PACKETNAME_INSERT(GU_BANK_ITEM_DELETE_RES);
	PACKETNAME_INSERT(GU_SOCIAL_ACTION);                              // Use Social Actions
	PACKETNAME_INSERT(GU_SCOUTER_INDICATOR_RES);                      // Scouter combat power measurement results
	PACKETNAME_INSERT(GU_SCOUTER_PREDICT_RES);
	PACKETNAME_INSERT(GU_SCOUTER_EQUIP_CHECK_RES);
	PACKETNAME_INSERT(GU_SCOUTER_CHIP_REMOVE_ALL_RES);
	PACKETNAME_INSERT(GU_TS_CONFIRM_STEP_RES);						// Trigger Step Progress Response
	PACKETNAME_INSERT(GU_TS_UPDATE_SYNC_NFY);							// Trigger synchronous progress notification
	PACKETNAME_INSERT(GU_TS_UPDATE_STATE);							// Trigger failure status update
	PACKETNAME_INSERT(GU_TS_UPDATE_EVENT_NFY);						// Trigger event update
	PACKETNAME_INSERT(GU_TS_EXCUTE_TRIGGER);							// Force client trigger execution
	PACKETNAME_INSERT(GU_TS_EXCUTE_TRIGGER_OBJECT_RES);				//
	PACKETNAME_INSERT(GU_TS_TRIGGER_OBJECT_DIALOG_NFY);				// TriggerObject Conversation
	PACKETNAME_INSERT(GU_TS_PC_DIALOG_NFY);							// PC Conversation
	PACKETNAME_INSERT(GU_TS_SKIP_CONTAINER);
	PACKETNAME_INSERT(GU_QUEST_ITEM_CREATE_NFY);						// Quest item creation notification
	PACKETNAME_INSERT(GU_QUEST_ITEM_DELETE_NFY);						// Quest item deletion notification
	PACKETNAME_INSERT(GU_QUEST_ITEM_UPDATE_NFY);						// Quest item change notification
	PACKETNAME_INSERT(GU_QUEST_ITEM_MOVE_RES);						// Quest item movement response
	PACKETNAME_INSERT(GU_QUEST_ITEM_DELETE_RES);						// Quest item deletion response
	PACKETNAME_INSERT(GU_QUEST_SVREVT_START_NFY);						// Quest event begins
	PACKETNAME_INSERT(GU_QUEST_SVREVT_END_NFY);						// Quest event ends
	PACKETNAME_INSERT(GU_QUEST_SVREVT_UPDATE_NFY);					// Quest Event Update
	PACKETNAME_INSERT(GU_QUEST_GIVEUP_RES);							// Quest abandonment response
	PACKETNAME_INSERT(GU_QUEST_SHARE_NFY);							// Share Quest
	PACKETNAME_INSERT(GU_QUEST_RESET_NFY);							// Deletes progress and completion information to the specified extent of the quest.
	PACKETNAME_INSERT(GU_QUEST_OBJECT_VISIT_RES);						// npc ); tobject visit event
	PACKETNAME_INSERT(GU_QUEST_FORCED_COMPLETION_NFY);				// Force quest completion settings (for testing)
	PACKETNAME_INSERT(GU_FREEBATTLE_CHALLENGE_RES);					// Free Battle match application response
	PACKETNAME_INSERT(GU_FREEBATTLE_ACCEPT_REQ);						// Free Battle Match Acceptance Request
	PACKETNAME_INSERT(GU_FREEBATTLE_CANCEL_NFY);						// Free Battle Match Cancellation
	PACKETNAME_INSERT(GU_FREEBATTLE_START_NFY);						// Free battle begins
	PACKETNAME_INSERT(GU_FREEBATTLE_OUTSIDE_NFY);						// Out of range for free battle
	PACKETNAME_INSERT(GU_FREEBATTLE_INSIDE_NFY);						// Free battle range entered
	PACKETNAME_INSERT(GU_FREEBATTLE_END_NFY);							// Free battle ends
	PACKETNAME_INSERT(GU_QUICK_SLOT_UPDATE_RES);						// Quick slot update
	PACKETNAME_INSERT(GU_QUICK_SLOT_DEL_NFY);							// Delete quick slot	
	PACKETNAME_INSERT(GU_QUICK_SLOT_INFO);							// QuickSlot Load
	PACKETNAME_INSERT(GU_PET_CHAR_INFO);
	PACKETNAME_INSERT(GU_PET_SKILL_INFO);
	PACKETNAME_INSERT(GU_PET_INFO_END);
	PACKETNAME_INSERT(GU_PET_DESPAWNED_NFY);							// disappearance of pet
	PACKETNAME_INSERT(GU_PET_DISMISS_PET_RES);						// Result of pet's summon cancellation request
	PACKETNAME_INSERT(GU_ACTION_REPORT_MESSAGE);						// If you send the message you want to display with a reservation code index attached, the client displays it.
	PACKETNAME_INSERT(GU_TRADE_START_NFY);
	PACKETNAME_INSERT(GU_TRADE_START_RES);
	PACKETNAME_INSERT(GU_TRADE_OK_REQ);
	PACKETNAME_INSERT(GU_TRADE_ADD_NFY);
	PACKETNAME_INSERT(GU_TRADE_ADD_RES);
	PACKETNAME_INSERT(GU_TRADE_DEL_NFY);
	PACKETNAME_INSERT(GU_TRADE_DEL_RES);
	PACKETNAME_INSERT(GU_TRADE_MODIFY_NFY);
	PACKETNAME_INSERT(GU_TRADE_MODIFY_RES);
	PACKETNAME_INSERT(GU_TRADE_ZENNY_UPDATE_NFY);
	PACKETNAME_INSERT(GU_TRADE_ZENNY_UPDATE_RES);
	PACKETNAME_INSERT(GU_TRADE_END_NFY);
	PACKETNAME_INSERT(GU_TRADE_END_RES);
	PACKETNAME_INSERT(GU_TRADE_CANCEL_NFY);
	PACKETNAME_INSERT(GU_TRADE_CANCEL_RES);
	PACKETNAME_INSERT(GU_TRADE_DENY_RES);
	PACKETNAME_INSERT(GU_GUILD_NAME_CHANGED_NFY);					    // Guild name change notice
	PACKETNAME_INSERT(GU_GUILD_CREATE_RES);						    // Guild creation request result
	PACKETNAME_INSERT(GU_GUILD_INVITE_RES);						    // Guild invitation results
	PACKETNAME_INSERT(GU_TOBJECT_UPDATE_STATE);						// Trigger object state update
	PACKETNAME_INSERT(GU_TOBJECT_ACTION_ATTACK);						// Trigger object damage
	PACKETNAME_INSERT(GU_TUTORIAL_HINT_UPDATE_RES);					// Hint flag update
	PACKETNAME_INSERT(GU_TELECAST_MESSAGE_BEG_NFY);					// Start broadcast message notification
	PACKETNAME_INSERT(GU_TELECAST_MESSAGE_END_NFY);					// End of broadcast message notification
	PACKETNAME_INSERT(GU_BROAD_MESSAGE_BEG_NFY);						// Start broadcast message
	PACKETNAME_INSERT(GU_BROAD_MESSAGE_END_NFY);						// End of broadcast message
	PACKETNAME_INSERT(GU_MINI_NARRATION_NFY);							// mini narration
	PACKETNAME_INSERT(GU_PROGRESS_MESSAGE_NFY);						// Time Machine Progress Message Notification
	PACKETNAME_INSERT(GU_DIRECTION_INDICATE_NFY);						// Direction notice
	PACKETNAME_INSERT(GU_TIMEQUEST_START_NFY);						// Time Machine Quest Start Notification
	PACKETNAME_INSERT(GU_TIMEQUEST_START_EXCEPTION_NFY);				// Failed to enter Time Machine Quest World (not transmitted upon success)
	PACKETNAME_INSERT(GU_TIMEQUEST_LEAVE_NFY);						// Time Machine Quest Exit Notice
	PACKETNAME_INSERT(GU_TIMEQUEST_COUNTDOWN_NFY);					// Time Machine Quest Countdown Notice
	PACKETNAME_INSERT(GU_TIMEQUEST_REWARD_NFY);						// Time Machine Quest Reward Notice
	PACKETNAME_INSERT(GU_TIMEQUEST_INFORMATION_NFY);				    // Time Machine Quest Stage Information Notice
	PACKETNAME_INSERT(GU_TIMEQUEST_UPDATE_GAME_STATE);				// Time Machine Quest Game Status Update
	PACKETNAME_INSERT(GU_TIMEQUEST_UPDATE_KILL_COUNT);				// Time Machine Quest Player Kill Count Update
	PACKETNAME_INSERT(GU_TIMEQUEST_UPDATE_COUPON_COUNT);				// Time Machine Quest coupon information update
	PACKETNAME_INSERT(GU_TIMEQUEST_UPDATE_TMQ_POINT);					// Time Machine Quest TMQ Points Update
	PACKETNAME_INSERT(GU_TIMEQUEST_UPDATE_GAME_TIME);					// Time Machine Quest Game Time Update
	PACKETNAME_INSERT(GU_RANKBATTLE_INFO_RES);						// basic information
	PACKETNAME_INSERT(GU_RANKBATTLE_JOIN_RES);						// application
	PACKETNAME_INSERT(GU_RANKBATTLE_JOIN_NFY);						// Notification of application to member
	PACKETNAME_INSERT(GU_RANKBATTLE_LEAVE_RES);						// cancellation
	PACKETNAME_INSERT(GU_RANKBATTLE_LEAVE_NFY);						// Cancellation party member notification
	PACKETNAME_INSERT(GU_RANKBATTLE_MATCH_START_NFY);					// game starts
	PACKETNAME_INSERT(GU_RANKBATTLE_MATCH_CANCELED_NFY);				// Match is canceled
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_STATE_UPDATE_NFY);			// Update RankBattle Battle State (state of the arena)
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_TEAM_INFO_NFY);			// RankBattle Team information notification
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_PLAYER_STATE_NFY);			// RankBattle Player status notification (off-site); death, etc.)
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_KILLSCORE_UPDATE_NFY);		// RankBattle KillScore Update
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_STAGE_FINISH_NFY);			// RankBattle Stage Finish -Stage Finish
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_MATCH_FINISH_NFY);			// RankBattle Battle Finish -Finish the match
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_END_NFY);					// Notify PC when RankBattle ends (since the battle ends at different times for each PC)
	PACKETNAME_INSERT(GU_RANKBATTLE_BATTLE_FORCED_LEAVE_NFY);			// Forced WorldLeave in RankBattle (too long loading state, etc.)
	PACKETNAME_INSERT(GU_RANKBATTLE_TOTAL_SCORE_UPDATE_NFY);			// Personal record update
	PACKETNAME_INSERT(GU_DRAGONBALL_CHECK_RES);						// Dragon Ball UI 7 placement OK
	PACKETNAME_INSERT(GU_DRAGONBALL_REWARD_RES);						// Request to select a reward for collecting all Dragon Balls
	PACKETNAME_INSERT(GU_DRAGONBALL_COLLECT_NFY);						// Dragon Ball Schedule Time Over Notice
	PACKETNAME_INSERT(GU_DRAGONBALL_SCHEDULE_INFO);					// Dragon Ball collection period information
	PACKETNAME_INSERT(GU_PRIVATESHOP_CREATE_RES);						// Create a personal store [6/28/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_CREATE_NFY);						// Private store exception [1/31/2008 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_EXIT_RES);						// Closing private stores [6/28/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_OPEN_RES);						// Please set the status to Open in your personal store [6/28/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_OPEN_NFY);						// [7/31/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_CLOSE_RES);						// Please set the status to Close in your personal store [6/28/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_CLOSE_NFY);						// [7/31/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_INSERT_RES);				// Response to adding items to personal store [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_UPDATE_RES);				// Response to item modification in personal store [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_DELETE_RES);				// Response to item deletion in personal store [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_BUYING_RES);				// Item Purchase Response [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_BUYING_NFY);				// [7/31/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ENTER_RES);						// Guest Entry Response [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_LEAVE_RES);						// Guest exit response [6/29/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_DATA_INFO);					// Item Data [7/2/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_SELECT_RES);				// [7/19/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_SELECT_NFY);				// [7/19/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_ITEM_STATE_NFY);					// [7/31/2007 SGpro]
	PACKETNAME_INSERT(GU_PRIVATESHOP_LEAVE_NFY);						// [8/3/2007 SGpro]
	PACKETNAME_INSERT(GU_TUTORIAL_WAIT_NFY);							// Tutorial waiting notification 
	PACKETNAME_INSERT(GU_TUTORIAL_WAIT_CANCEL_RES);					// Tutorial standby cancellation request response
	PACKETNAME_INSERT(GU_TUTORIAL_PLAY_QUIT_RES);						// Response to request to cancel tutorial play
	PACKETNAME_INSERT(GU_MAIL_START_RES);
	PACKETNAME_INSERT(GU_MAIL_SEND_RES);
	PACKETNAME_INSERT(GU_MAIL_READ_RES);
	PACKETNAME_INSERT(GU_MAIL_RELOAD_NFY);
	PACKETNAME_INSERT(GU_MAIL_DEL_RES);
	PACKETNAME_INSERT(GU_MAIL_RETURN_RES);
	PACKETNAME_INSERT(GU_MAIL_RELOAD_RES);
	PACKETNAME_INSERT(GU_MAIL_LOAD_RES);
	PACKETNAME_INSERT(GU_MAIL_LOAD_DATA);
	PACKETNAME_INSERT(GU_MAIL_LOAD_INFO);
	PACKETNAME_INSERT(GU_MAIL_ITEM_RECEIVE_RES);
	PACKETNAME_INSERT(GU_MAIL_LOCK_RES);
	PACKETNAME_INSERT(GU_MAIL_CLOSE_NFY);
	PACKETNAME_INSERT(GU_MAIL_MULTI_DEL_RES);
	PACKETNAME_INSERT(GU_PORTAL_INFO);
	PACKETNAME_INSERT(GU_PORTAL_ADD_RES);
	PACKETNAME_INSERT(GU_PORTAL_RES);
	PACKETNAME_INSERT(GU_WAR_FOG_INFO);
	PACKETNAME_INSERT(GU_WAR_FOG_UPDATE_RES);
	PACKETNAME_INSERT(GU_MOB_LUCKY_DROP_NFY);
	PACKETNAME_INSERT(GU_ITEM_UPGRADE_ALL_NFY);
	PACKETNAME_INSERT(GU_BOT_BOTCAUTION_NFY);                        // Bot warning [2/20/2008 SGpro]
	PACKETNAME_INSERT(GU_UPDATE_CHAR_REPUTATION);
	PACKETNAME_INSERT(GU_GUILD_FUNCTION_ADD_RES);
	PACKETNAME_INSERT(GU_GUILD_GIVE_ZENNY_RES);
	PACKETNAME_INSERT(GU_GUILD_BANK_START_RES);
	PACKETNAME_INSERT(GU_GUILD_BANK_MOVE_RES);
	PACKETNAME_INSERT(GU_GUILD_BANK_MOVE_STACK_RES);
	PACKETNAME_INSERT(GU_GUILD_BANK_END_RES);
	PACKETNAME_INSERT(GU_GUILD_BANK_ZENNY_INFO);
	PACKETNAME_INSERT(GU_GUILD_BANK_ITEM_INFO);
	PACKETNAME_INSERT(GU_GUILD_BANK_ZENNY_RES);
	PACKETNAME_INSERT(GU_GUILD_CREATE_MARK_RES);
	PACKETNAME_INSERT(GU_GUILD_CHANGE_MARK_RES);
	PACKETNAME_INSERT(GU_GUILD_MARK_CHANGED_NFY);
	PACKETNAME_INSERT(GU_CROSSFIRE_RES);
	PACKETNAME_INSERT(GU_BANK_LOAD_RES);
	PACKETNAME_INSERT(GU_GUILD_CHANGE_NAME_RES);
	PACKETNAME_INSERT(GU_PARTY_SHARETARGET_RES);						// [3/28/2008 SGpro]
	PACKETNAME_INSERT(GU_PARTY_SHARETARGET_NFY);						// [3/28/2008 SGpro]
	PACKETNAME_INSERT(GU_RIDE_ON_BUS_RES);
	PACKETNAME_INSERT(GU_RIDE_OFF_BUS_RES);
	PACKETNAME_INSERT(GU_TRANSFORM_CANCEL_RES);
	PACKETNAME_INSERT(GU_SHOP_ITEM_IDENTIFY_RES);
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_STATE_UPDATE_NFY);						// Match
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_TEAM_INFO_NFY);				// Preliminary team information
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_PLAYER_STATE_NFY);			//
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_UPDATE_SCORE_NFY);			// Preliminary Score Update
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_TEAM_SCORE_NFY);				// Preliminary team score information ); Information for Intruders
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_SELECTION_NFY);				// Dice display in case of tie in preliminary round
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_STAGE_FINISH_NFY);			// Preliminary stage finish notification
	PACKETNAME_INSERT(GU_MATCH_MINORMATCH_MATCH_FINISH_NFY);
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_STATE_UPDATE_NFY);			//
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_TEAM_INFO_NFY);				// Final team information
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_PLAYER_STATE_NFY);			//
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_UPDATE_SCORE_NFY);			// Final Score Update
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_STAGE_FINISH_NFY);			// Final stage finish notification
	PACKETNAME_INSERT(GU_MATCH_MAJORMATCH_MATCH_FINISH_NFY);			// Final match finish notification
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_STATE_UPDATE_NFY);			//
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_TEAM_INFO_NFY);				// Final Team Information
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_PLAYER_STATE_NFY);			//
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_UPDATE_SCORE_NFY);			// Final Score Update
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_STAGE_FINISH_NFY);			// Final stage finish notification
	PACKETNAME_INSERT(GU_MATCH_FINALMATCH_MATCH_FINISH_NFY);			// Final match finish notification
	PACKETNAME_INSERT(GU_MATCH_AWARDING_NFY);							// Awards Ceremony Results
	PACKETNAME_INSERT(GU_SKILL_CONFUSE_TARGET_NFY);					    // Notification of attack target when in Confuse state
	PACKETNAME_INSERT(GU_SKILL_TERROR_COURSE_CHANGE_NFY);			    // Direction change notification when in Terror state
	PACKETNAME_INSERT(GU_DICE_ROLL_RES);							    // Action Skill Rolling the Dice
	PACKETNAME_INSERT(GU_DICE_ROLLED_NFY);							    // Action Skill Rolling the Dice
	PACKETNAME_INSERT(GU_BUDOKAI_STATE_INFO_NFY);					    // Transmit the current status of the World's First Martial Arts Council
	PACKETNAME_INSERT(GU_BUDOKAI_UPDATE_STATE_NFY);					    // World's First Martial Arts Club: main state update
	PACKETNAME_INSERT(GU_BUDOKAI_UPDATE_MATCH_STATE_NFY);			    // World's First Martial Arts Club: match state update
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_INDIVIDUAL_RES);				    // personal registration
	PACKETNAME_INSERT(GU_BUDOKAI_LEAVE_INDIVIDUAL_RES);				    // personal cancellation
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_TEAM_INFO_RES);				    // team points
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_TEAM_RES);					    // Team Registration
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_TEAM_NFY);					    // Team Registration Reminder
	PACKETNAME_INSERT(GU_BUDOKAI_LEAVE_TEAM_RES);					    // Cancel team registration
	PACKETNAME_INSERT(GU_BUDOKAI_LEAVE_TEAM_NFY);					    // Team Registration Cancellation Notice
	PACKETNAME_INSERT(GU_BUDOKAI_LEAVE_TEAM_MEMBER_RES);			    // Cancel team member
	PACKETNAME_INSERT(GU_BUDOKAI_LEAVE_TEAM_MEMBER_NFY);			    // Team Member Cancellation Notification
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_INFO_RES);					    // Participation information
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_STATE_RES);					    // participation status
	PACKETNAME_INSERT(GU_BUDOKAI_JOIN_STATE_NFY);					    // Participation status notification
	PACKETNAME_INSERT(GU_BUDOKAI_MUDOSA_INFO_RES);					    // Martial arts information
	PACKETNAME_INSERT(GU_BUDOKAI_MUDOSA_TELEPORT_RES);				    // Martial Artist Teleport
	PACKETNAME_INSERT(GU_BUDOKAI_PROGRESS_MESSAGE_NFY);				    // Game progress information notification (notice)
	PACKETNAME_INSERT(GU_BUDOKAI_SOCIAL_ACTION_NFY);
	PACKETNAME_INSERT(GU_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_RES);		    // Request teleportation to World's First Martial Arts Server
	PACKETNAME_INSERT(GU_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_RES);		    // Move from the World's First Martial Arts server to the original server.
	PACKETNAME_INSERT(GU_BUDOKAI_GM_MATCH_PROGRESS_INFO_RES);		    // Current game progress list
	PACKETNAME_INSERT(GU_BUDOKAI_GM_MATCH_ARENA_ENTER_RES);			    // Enter the stadium
	PACKETNAME_INSERT(GU_BUDOKAI_GM_MATCH_ARENA_LEAVE_RES);			    // exit the stadium
	PACKETNAME_INSERT(GU_DISCONNECTED_NFY);
	PACKETNAME_INSERT(GU_BOT_BOTCAUTION_HELPME_NFY);				    // Help Me Alert [5/27/2008 SGpro]
	PACKETNAME_INSERT(GU_SCOUTER_TURN_ON_NFY);
	PACKETNAME_INSERT(GU_SCOUTER_TURN_OFF_NFY);
	PACKETNAME_INSERT(GU_SCOUTER_BROKEN_NFY);
	PACKETNAME_INSERT(GU_SCOUTER_ITEM_SELL_RES);
	PACKETNAME_INSERT(GU_SHOP_EVENTITEM_START_RES);					    // [7/15/2008 SGpro]
	PACKETNAME_INSERT(GU_SHOP_EVENTITEM_BUY_RES);					    // EVENT ITEM Purchase [7/11/2008 SGpro]
	PACKETNAME_INSERT(GU_SHOP_EVENTITEM_END_RES);					    // [7/15/2008 SGpro]
	PACKETNAME_INSERT(GU_ITEM_REPLACE);								    // ITEM Replacement [7/11/2008 SGpro]
	PACKETNAME_INSERT(GU_SHOP_GAMBLE_BUY_RES);						    // EVENT ITEM Purchase [7/11/2008 SGpro]
	PACKETNAME_INSERT(GU_PARTY_DUNGEON_DIFF_NFY);
	PACKETNAME_INSERT(GU_PARTY_DUNGEON_DIFF_RES);
	PACKETNAME_INSERT(GU_PARTY_DUNGEON_INIT_NFY);
	PACKETNAME_INSERT(GU_PARTY_DUNGEON_INIT_RES);
	PACKETNAME_INSERT(GU_UPDATE_CHAR_SP);
	PACKETNAME_INSERT(GU_SKILL_INIT_RES);
	PACKETNAME_INSERT(GU_SKILL_REMOVE_NFY);
	PACKETNAME_INSERT(GU_HTB_REMOVE_NFY);
	PACKETNAME_INSERT(GU_TELEPORT_PROPOSAL_NFY);
	PACKETNAME_INSERT(GU_TELEPORT_CONFIRM_RES);
	PACKETNAME_INSERT(GU_AVATAR_PETITION_INFO);
	PACKETNAME_INSERT(GU_GAME_COMMON_MSG_NFY);                  
	PACKETNAME_INSERT( GU_HOIPOIMIX_RECIPE_REG_NFY );				    // Recipe registration
	PACKETNAME_INSERT( GU_HOIPOIMIX_ITEM_RECIPE_INFO );
	PACKETNAME_INSERT( GU_DYNAMIC_OBJECT_UPDATE_STATE );
	PACKETNAME_INSERT( GU_HOIPOIMIX_ITEM_MAKE_EXP_NFY );		        // Hoipoi mix level up or experience level update
	PACKETNAME_INSERT( GU_CHAR_TARGET_LOST_NFY );
	PACKETNAME_INSERT( GU_CHAR_GUARD_CRASHED_NFY );		                // Guard is forced off by Skill Ability
	PACKETNAME_INSERT( GU_UPDATE_CHAR_RP_BALL );
	PACKETNAME_INSERT( GU_UPDATE_CHAR_RP_BALL_MAX );
	PACKETNAME_INSERT( GU_AVATAR_RP_INCREASE_START_NFY );
	PACKETNAME_INSERT( GU_AVATAR_RP_DECREASE_START_NFY );
	PACKETNAME_INSERT( GU_AVATAR_RP_INCREASE_STOP_NFY );
	PACKETNAME_INSERT( GU_HTB_LAST_STEP_CHANGED_NFY );
	PACKETNAME_INSERT( GU_CHAR_CHARGE_CANCELED_NFY );
	PACKETNAME_INSERT( GU_CHAR_REFRESH_LP_EP );
	PACKETNAME_INSERT( GU_CHAR_NONBATTLEACTIONPATTERNSET_UNITIDX_NFY );
	PACKETNAME_INSERT( GU_VEHICLE_START_NFY );			                 // Vehicle start location notification
	PACKETNAME_INSERT( GU_VEHICLE_END_RES );						     // Notification of end of vehicle use
	PACKETNAME_INSERT( GU_VEHICLE_END_NFY );
	PACKETNAME_INSERT( GU_VEHICLE_STUNT_NFY );					         // Press space bar (vehicle)
	PACKETNAME_INSERT( GU_SKILL_PASSIVE_EFFECT_APPLIED_NFY );
	PACKETNAME_INSERT( GU_AVATAR_UPDATED_SKILL_DATA_INFO );
	PACKETNAME_INSERT( GU_MONSTER_TRANSFORMED_NFY );
	PACKETNAME_INSERT( GU_DOJO_CREATE_RES );
	PACKETNAME_INSERT( GU_DOJO_DELETE_RES );
	PACKETNAME_INSERT( GU_DOJO_FUNCTION_ADD_RES );
	PACKETNAME_INSERT( GU_DOGI_CREATE_RES );							  // Uniform creation
	PACKETNAME_INSERT( GU_DOGI_CHANGE_RES );							  // Uniform change
	PACKETNAME_INSERT( GU_DOGI_UPDATE_NFY );							  // Uniform change notification
	PACKETNAME_INSERT( GU_GUILD_DOGI_CREATE_RES );
	PACKETNAME_INSERT( GU_GUILD_DOGI_CHANGE_RES );
	PACKETNAME_INSERT( GU_CHILD_ADULT_SWITCHED_NFY );
	PACKETNAME_INSERT( GU_CHANGE_CLASS_AUTHORITY_CHANGED_NFY );
	PACKETNAME_INSERT( GU_PLAY_BGM );
	PACKETNAME_INSERT( GU_DOJO_MARK_CHANGED_NFY );
	PACKETNAME_INSERT( GU_DOJO_LEVEL_CHANGED_NFY );
	PACKETNAME_INSERT( GU_UPDATE_CHAR_NETP );
	PACKETNAME_INSERT( GU_DOJO_SCRAMBLE_RES );							  // Response to application for dojo competition
	PACKETNAME_INSERT( GU_DOJO_SCRAMBLE_RESPONSE_RES );					  // Response to processing of application response for Dojo Competition
	PACKETNAME_INSERT( GU_NETMARBLEMEMBERIP_NFY );
	PACKETNAME_INSERT( GU_BUS_LOCATION_NFY );
	PACKETNAME_INSERT( GU_BUS_LOCATION_ERASED_NFY );
	PACKETNAME_INSERT( GU_BUS_LOCATION_RESET_ALL_NFY );
	PACKETNAME_INSERT( GU_ITEM_EXPIRED_NFY );
	PACKETNAME_INSERT( GU_SHOP_NETPYITEM_START_RES );
	PACKETNAME_INSERT( GU_SHOP_NETPYITEM_BUY_RES );
	PACKETNAME_INSERT( GU_SHOP_NETPYITEM_END_RES );
	PACKETNAME_INSERT( GU_DURATION_ITEM_BUY_RES );
	PACKETNAME_INSERT( GU_DURATION_RENEW_RES );
	PACKETNAME_INSERT( GU_CHAR_REFRESH_BATTLE_ATTRIBUTE_MODIFIER );
	PACKETNAME_INSERT( GU_CHAR_RANKPOINT_RESET_NFY );
	PACKETNAME_INSERT( GU_DOJO_NPC_INFO_RES );
	PACKETNAME_INSERT( GU_GAMEGUARD_AUTH_ANSWER_REQ );
	PACKETNAME_INSERT( GU_DOJO_SEAL_ATTACK_BEGIN_NFY );
	PACKETNAME_INSERT( GU_DOJO_SEAL_ATTACK_END_NFY );
	PACKETNAME_INSERT( GU_DOJO_SEAL_CURRENT_STATE_NFY );
	PACKETNAME_INSERT( GU_INVENTORY_CAPSULE_UNLOCK_NFY );
	PACKETNAME_INSERT( GU_DOJO_SCRAMBLE_SHIFT_SEAL_STATE_NFY );

	PACKETNAME_INSERT( TU_ENTER_CHAT_RES );
	PACKETNAME_INSERT( TU_DISCONNECT );
	PACKETNAME_INSERT( TU_DISCONNECTED_NFY );
	PACKETNAME_INSERT( TU_HEARTBEAT );
	PACKETNAME_INSERT( TU_SYSTEM_DISPLAY_TEXT );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_SAY );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_SHOUT );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_WHISPER );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_WHISPER_FAILED_NFY );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_PARTY );
	PACKETNAME_INSERT( TU_CHAT_MESSAGE_GUILD );
	// Guild Creation/Disbanding
	PACKETNAME_INSERT( TU_GUILD_CREATED_NFY );						// Notice that a guild has been created
	PACKETNAME_INSERT( TU_GUILD_INFO );								// Guild Information
	PACKETNAME_INSERT( TU_GUILD_MEMBER_INFO );						// Guild member information
	// Guild Member Invitation/Leaving/Kicking Out
	PACKETNAME_INSERT( TU_GUILD_DISBAND_RES );						// Results of guild disbandment request
	PACKETNAME_INSERT( TU_GUILD_BEING_DISBANDED_NFY );				// Notice on guild disbandment standby status
	PACKETNAME_INSERT( TU_GUILD_DISBAND_CANCEL_RES );				// Results of guild disbandment cancellation request
	PACKETNAME_INSERT( TU_GUILD_DISBAND_CANCELED_NFY );				// Notice that guild disbandment has been cancelled.
	PACKETNAME_INSERT( TU_GUILD_DISBANDED_NFY );						// Announcement that the actual guild has been disbanded
	PACKETNAME_INSERT( TU_GUILD_INVITED_NFY );						// Notification that you have been invited to the guild
	PACKETNAME_INSERT( TU_GUILD_RESPONSE_INVITATION_RES );			// Result of response to guild invitation
	PACKETNAME_INSERT( TU_GUILD_MEMBER_JOINED_NFY );					// New guild member registration notice
	PACKETNAME_INSERT( TU_GUILD_INVITATION_DECLINED_NFY );			// Decline guild invitation
	PACKETNAME_INSERT( TU_GUILD_INVITATION_EXPIRED_NFY );			// Validity time of guild invitation
	PACKETNAME_INSERT( TU_GUILD_LEAVE_RES );							// Results of guild withdrawal request
	PACKETNAME_INSERT( TU_GUILD_MEMBER_LEFT_NFY );					// Guild member withdrawal notice
	PACKETNAME_INSERT( TU_GUILD_KICK_OUT_RES );						// Result of guild member¡¯s forced withdrawal request
	PACKETNAME_INSERT( TU_GUILD_MEMBER_KICKED_OUT_NFY );				// Notice of forced withdrawal from guild members
	// Appointment of Guild Master/Guild Second Master
	PACKETNAME_INSERT( TU_GUILD_APPOINT_SECOND_MASTER_RES );			// Consequences of Appointment of Second Master
	PACKETNAME_INSERT( TU_GUILD_SECOND_MASTER_APPOINTED_NFY );		// Notice of Appointment of Second Master
	PACKETNAME_INSERT( TU_GUILD_DISMISS_SECOND_MASTER_RES );			// Consequences of dismissal of Second Master
	PACKETNAME_INSERT( TU_GUILD_SECOND_MASTER_DISMISSED_NFY );		// Notice of removal of Second Master from position
	PACKETNAME_INSERT( TU_GUILD_CHANGE_GUILD_MASTER_RES );			// Results of the Guild Master's transition
	PACKETNAME_INSERT( TU_GUILD_GUILD_MASTER_CHANGED_NFY );			// Guild Master Change Notice
	// Sync. of Guild Members' Info
	PACKETNAME_INSERT( TU_GUILD_MEMBER_POSITION_CHANGED_NFY );		// Guild member location change notification
	PACKETNAME_INSERT( TU_GUILD_MEMBER_CLASS_CHANGED_NFY );			// Guild member job change notification
	PACKETNAME_INSERT( TU_GUILD_MEMBER_LEVEL_CHANGED_NFY );			// Guild member level change notification
	PACKETNAME_INSERT( TU_GUILD_MEMBER_REPUTATION_CHANGED_NFY );		// Guild member reputation change notification
	PACKETNAME_INSERT( TU_GUILD_MEMBER_ONLINE_NFY );					// Guild member game entry notification
	PACKETNAME_INSERT( TU_GUILD_MEMBER_OFFLINE_NFY );				// Guild member game exit notice
	PACKETNAME_INSERT( TU_FRIEND_ADD_RES );		// add friend
	PACKETNAME_INSERT( TU_FRIEND_DEL_RES );		// delete friend
	PACKETNAME_INSERT( TU_FRIEND_MOVE_RES );		// Go to Friends -> Blacklist
	PACKETNAME_INSERT( TU_FRIEND_LIST_INFO );	// Friend list information
	PACKETNAME_INSERT( TU_FRIEND_BLACK_ADD_RES );		// Add friend blacklist
	PACKETNAME_INSERT( TU_FRIEND_BLACK_DEL_RES );		// Delete friend blacklist
	PACKETNAME_INSERT( TU_FRIEND_INFO );					// Online friend details
	PACKETNAME_INSERT( TU_FRIEND_INFO_CHANGE );			// Friend status change notification
	PACKETNAME_INSERT( TU_RANKBATTLE_RANK_LIST_RES );
	PACKETNAME_INSERT( TU_RANKBATTLE_RANK_FIND_CHARACTER_RES );
	PACKETNAME_INSERT( TU_RANKBATTLE_RANK_COMPARE_DAY_RES );	
	PACKETNAME_INSERT( TU_GUILD_REPUTATION_CHANGE_NFY );					// Guild reputation change notification
	PACKETNAME_INSERT( TU_GUILD_FUNCTION_CHANGE_NFY );
	PACKETNAME_INSERT( TU_GUILD_CHANGE_NOTICE_NFY );
	PACKETNAME_INSERT( TU_GUILD_CHANGE_NOTICE_RES );
	PACKETNAME_INSERT( TU_GUILD_GIVE_ZENNY_NFY );
	PACKETNAME_INSERT( TU_TMQ_RECORD_LIST_RES );
	PACKETNAME_INSERT( TU_TMQ_MEMBER_LIST_RES );
	PACKETNAME_INSERT( TU_BUDOKAI_NOTICE_NFY );						// World's First Martial Arts Festival Notice
	PACKETNAME_INSERT( TU_BUDOKAI_TOURNAMENT_INDIVIDUAL_LIST_RES );
	PACKETNAME_INSERT( TU_BUDOKAI_TOURNAMENT_INDIVIDUAL_INFO_RES );
	PACKETNAME_INSERT( TU_BUDOKAI_TOURNAMENT_TEAM_LIST_RES );
	PACKETNAME_INSERT( TU_BUDOKAI_TOURNAMENT_TEAM_INFO_RES );
	PACKETNAME_INSERT( TU_PETITION_CHAT_START_REQ );						// Calm chat request [by sooshia 2008-10-15]
	PACKETNAME_INSERT( TU_PETITION_CHAT_GM_SAY_REQ );				// What GM said [by sooshia 2008-10-16]
	PACKETNAME_INSERT( TU_PETITION_CHAT_USER_SAY_RES );				// [ by sooshia 2008-10-16 ]
	PACKETNAME_INSERT( TU_PETITION_CHAT_GM_END_NFY );					// [ by sooshia 2008-10-17 ]
	PACKETNAME_INSERT( TU_PETITION_USER_INSERT_RES );					// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( TU_PETITION_CONTENT_MODIFY_RES );					// [ by sooshia 2008-10-18 ]

	PACKETNAME_INSERT( TU_PETITION_USER_CANCEL_RES );					// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( TU_PETITION_FINISH_NFY );
	PACKETNAME_INSERT( TU_DOJO_CREATED_NFY );
	PACKETNAME_INSERT( TU_DOJO_DESTROYED_NFY );
	PACKETNAME_INSERT( TU_DOJO_BRIEF_NFY );
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_NFY );							// It notifies you again when the guild leader goes out or a response is needed.
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_INFORM_NFY );					// Broadcast message before painting
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_REJECT_NFY );					// When you are rejected by the school you applied for
	PACKETNAME_INSERT( TU_DOJO_BUDOKAI_SEED_ADD_RES );
	PACKETNAME_INSERT( TU_DOJO_BUDOKAI_SEED_DEL_RES );
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_POINT_NFY );						// Dojo score broadcast message
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_SHIEFT_SEAL_STATE_NFY );			// Stamp seal acquisition broadcast
	PACKETNAME_INSERT( TU_DOJO_NOTICE_CHANGE_RES );
	PACKETNAME_INSERT( TU_DOJO_NOTICE_CHANGE_NFY );
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_RECEIVE_NFY );					// When the school you applied for is accepted
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_RECEIVE_INFO_NFY );
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_REWARD_NFY );
	PACKETNAME_INSERT( TU_DOJO_SCRAMBLE_RESULT_NFY );

	PACKETNAME_INSERT( UA_LOGIN_REQ );
	PACKETNAME_INSERT( UA_LOGIN_DISCONNECT_REQ );

	PACKETNAME_INSERT( UC_LOGIN_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_SERVERLIST_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_SERVERLIST_ONE_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_ADD_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_DEL_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_SELECT_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_EXIT_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_LOAD_REQ );
	PACKETNAME_INSERT( UC_CHARACTER_DEL_CANCEL_REQ );					// Changed due to duplicate name
	PACKETNAME_INSERT( UC_CONNECT_WAIT_CHECK_REQ );
	PACKETNAME_INSERT( UC_CONNECT_WAIT_CANCEL_REQ );						// standby cancel
	PACKETNAME_INSERT( UC_CHARACTER_RENAME_REQ );

	PACKETNAME_INSERT( UG_PING );
	PACKETNAME_INSERT( UG_GAME_ENTER_REQ );
	PACKETNAME_INSERT( UG_GAME_LEAVE_REQ );									// Leave the game
	PACKETNAME_INSERT( UG_AUTH_KEY_FOR_COMMUNITY_SERVER_REQ );				// Community server authentication key request
	PACKETNAME_INSERT( UG_ENTER_WORLD );										// Enter the world
	PACKETNAME_INSERT( UG_SERVER_COMMAND );									// server command
	PACKETNAME_INSERT( UG_CHAR_READY_FOR_COMMUNITY_SERVER_NFY );				// Notification that data is ready to be transferred to the community server
	PACKETNAME_INSERT( UG_CHAR_READY_TO_SPAWN );								// Loading completed (ready to enter spawning state)
	PACKETNAME_INSERT( UG_CHAR_READY );										// character preparation
	PACKETNAME_INSERT( UG_CHAR_MOVE );										// character movement
	PACKETNAME_INSERT( UG_CHAR_DEST_MOVE );									// Move character destination
	PACKETNAME_INSERT( UG_CHAR_CHANGE_HEADING );								// character rotation
	PACKETNAME_INSERT( UG_CHAR_CHANGE_DIRECTION_ON_FLOATING );				// Direction facing when character jumps/falls
	PACKETNAME_INSERT( UG_CHAR_FOLLOW_MOVE );								// Follow character target
	PACKETNAME_INSERT( UG_CHAR_DASH_KEYBOARD );								// Start keyboard dash
	PACKETNAME_INSERT( UG_CHAR_DASH_MOUSE );									// Start Mouse dash
	PACKETNAME_INSERT( UG_CHAR_JUMP );										// jump start
	PACKETNAME_INSERT( UG_CHAR_JUMP_END );									// jump end
	PACKETNAME_INSERT( UG_CHAR_FALLING );									// Falling state start/end
	PACKETNAME_INSERT( UG_CHAR_TOGG_SITDOWN );								// Toggle sitting mode
	PACKETNAME_INSERT( UG_CHAR_TOGG_FIGHTING );								// Battle mode toggle
	PACKETNAME_INSERT( UG_CHAR_TARGET_SELECT );								// Select target
	PACKETNAME_INSERT( UG_CHAR_TARGET_INFO );								// Request for targeted information
	PACKETNAME_INSERT( UG_CHAR_TARGET_FACING );								// face to face
	PACKETNAME_INSERT( UG_CHAR_ATTACK_BEGIN );								// Attack start notification
	PACKETNAME_INSERT( UG_CHAR_ATTACK_END );									// Attack end notification
	PACKETNAME_INSERT( UG_CHAR_CHARGE );										// Character recharge
	PACKETNAME_INSERT( UG_CHAR_BLOCK_MODE );									// Start/exit Block mode
	PACKETNAME_INSERT( UG_CHAR_TELEPORT_REQ );								// Teleport request
	PACKETNAME_INSERT( UG_CHAR_BIND_REQ );									// bind request
	PACKETNAME_INSERT( UG_CHAR_REVIVAL_REQ );								// Resurrection Request
	PACKETNAME_INSERT( UG_CHAR_SERVER_CHANGE_REQ );							// Request to move to another game server
	PACKETNAME_INSERT( UG_CHAR_CHANNEL_CHANGE_REQ );							// Exit character -> Request to move to another server channel
	PACKETNAME_INSERT( UG_CHAR_EXIT_REQ );									// Exit character -> Request to move to character server
	PACKETNAME_INSERT( UG_GAME_EXIT_REQ );									// Quit the game
	PACKETNAME_INSERT( UG_CHAR_AWAY_REQ );
	PACKETNAME_INSERT( UG_CHAR_KEY_UPDATE_REQ );
	PACKETNAME_INSERT( UG_CHAR_DIRECT_PLAY_ACK );							// Response sent after completion of production
	PACKETNAME_INSERT( UG_CHAR_KNOCKDOWN_RELEASE_NFY );						// knockdown release
	PACKETNAME_INSERT( UG_CHAR_SKILL_REQ );									// Request to use skill
	PACKETNAME_INSERT( UG_SKILL_TARGET_LIST );								// Skill target list notification
	PACKETNAME_INSERT( UG_SKILL_LEARN_REQ );									// Skill training request
	PACKETNAME_INSERT( UG_SKILL_UPGRADE_REQ );								// Request to improve your skills
	PACKETNAME_INSERT( UG_SKILL_RP_BONUS_SETTING_REQ );						// Set the RP bonus type to be automatically used for each skill
	PACKETNAME_INSERT( UG_HTB_START_REQ );								    // HTB start request
	PACKETNAME_INSERT( UG_HTB_LEARN_REQ );									// Request to acquire HTB
	PACKETNAME_INSERT( UG_HTB_FORWARD_REQ );									// HTB progress
	PACKETNAME_INSERT( UG_HTB_RP_BALL_USE_REQ );
	PACKETNAME_INSERT( UG_BUFF_DROP_REQ );									// Buff release request
	PACKETNAME_INSERT( UG_ITEM_MOVE_REQ );									// Request to move an item
	PACKETNAME_INSERT( UG_ITEM_MOVE_STACK_REQ );								// Request to move item stack
	PACKETNAME_INSERT( UG_ITEM_DELETE_REQ );									// Request item deletion
	PACKETNAME_INSERT( UG_ITEM_EQUIP_REPAIR_REQ );							// Request to start repair
	PACKETNAME_INSERT( UG_ITEM_PICK_REQ );									// Request to pick up an item
	PACKETNAME_INSERT( UG_ITEM_REPAIR_REQ );
	PACKETNAME_INSERT( UG_ITEM_USE_REQ );									// Request to use item
	PACKETNAME_INSERT( UG_ITEM_UPGRADE_REQ );								// Item Upgrade
	PACKETNAME_INSERT( UG_ITEM_IDENTIFY_REQ );								// Check items with scouter parts
	PACKETNAME_INSERT( UG_ZENNY_PICK_REQ );									// Request to pick up money
	PACKETNAME_INSERT( UG_SHOP_START_REQ );									// Open a store
	PACKETNAME_INSERT( UG_SHOP_BUY_REQ );									// shop shopping
	PACKETNAME_INSERT( UG_SHOP_SELL_REQ );									// sell store items
	PACKETNAME_INSERT( UG_SHOP_END_REQ );									// Close store
	PACKETNAME_INSERT( UG_PARTY_CREATE_REQ );								// create a party
	PACKETNAME_INSERT( UG_PARTY_DISBAND_REQ );								// Breaking up the party
	PACKETNAME_INSERT( UG_PARTY_INVITE_REQ );								// Invite to a party
	PACKETNAME_INSERT( UG_PARTY_INVITE_CHARID_REQ );							// Invite to a party (using the other person¡¯s CharID)
	PACKETNAME_INSERT( UG_PARTY_INVITE_CHAR_NAME_REQ );						// Invite to a party (using the other person's name)
	PACKETNAME_INSERT( UG_PARTY_RESPONSE_INVITATION );						// Send a reply to a party invitation
	PACKETNAME_INSERT( UG_PARTY_LEAVE_REQ );									// Leave the party
	PACKETNAME_INSERT( UG_PARTY_KICK_OUT_REQ );								// Force member withdrawal
	PACKETNAME_INSERT( UG_PARTY_CHANGE_LEADER_REQ );							// Change party leader
	PACKETNAME_INSERT( UG_PARTY_CHANGE_ZENNY_LOOTING_METHOD_REQ );			// Changing Zenny Distribution Method
	PACKETNAME_INSERT( UG_PARTY_CHANGE_ITEM_LOOTING_METHOD_REQ );			// Change how items are distributed
	PACKETNAME_INSERT( UG_BANK_START_REQ );									// Warehouse item loading
	PACKETNAME_INSERT( UG_BANK_MOVE_REQ );									// Moving items from warehouse
	PACKETNAME_INSERT( UG_BANK_MOVE_STACK_REQ );								// Move stack items in Warehouse
	PACKETNAME_INSERT( UG_BANK_END_REQ );									// Close the warehouse.
	PACKETNAME_INSERT( UG_BANK_ZENNY_REQ );									// Save or withdraw from Warehouse.
	PACKETNAME_INSERT( UG_BANK_BUY_REQ );									// Increase the storage bag of the warehouse.
	PACKETNAME_INSERT( UG_BANK_ITEM_DELETE_REQ );							// Delete items from the warehouse.
	PACKETNAME_INSERT( UG_SCOUTER_INDICATOR_REQ );							// Scouter combat power measurement	
	PACKETNAME_INSERT( UG_SCOUTER_PREDICT_REQ );								// Scouter Upgrade Predictions	
	PACKETNAME_INSERT( UG_SCOUTER_EQUIP_CHECK_REQ );							// Check scouter opponent's equipped items
	PACKETNAME_INSERT( UG_SCOUTER_CHIP_REMOVE_ALL_REQ );						// Remove all scouter chips
	PACKETNAME_INSERT( UG_SOCIAL_ACTION );									// Use Social Actions
	PACKETNAME_INSERT( UG_TS_CONFIRM_STEP_REQ );								// Trigger progress request
	PACKETNAME_INSERT( UG_TS_UPDATE_STATE );									// Trigger failure status update
	PACKETNAME_INSERT( UG_TS_EXCUTE_TRIGGER_OBJECT );						// Excute Trigger Object
	PACKETNAME_INSERT( UG_QUEST_ITEM_MOVE_REQ );								// Quest item movement request
	PACKETNAME_INSERT( UG_QUEST_ITEM_DELETE_REQ );							// Request to delete quest item
	PACKETNAME_INSERT( UG_QUEST_GIVEUP_REQ );								// Request to give up quest item
	PACKETNAME_INSERT( UG_QUEST_SHARE );										// Request to share quest
	PACKETNAME_INSERT( UG_QUEST_OBJECT_VISIT_REQ );							// npc ); tobject visit event
	PACKETNAME_INSERT( UG_FREEBATTLE_CHALLENGE_REQ );						// Apply for Free Battle
	PACKETNAME_INSERT( UG_FREEBATTLE_ACCEPT_RES );							// Free Battle Match Acceptance Response
	PACKETNAME_INSERT( UG_QUICK_SLOT_UPDATE_REQ );							// Add or modify quick slots
	PACKETNAME_INSERT( UG_QUICK_SLOT_DEL_REQ );								// Delete quick slot
	PACKETNAME_INSERT( UG_PET_DISMISS_PET_REQ );								// Pet summon cancellation request
	PACKETNAME_INSERT( UG_TRADE_START_REQ );									// Request for exchange with the user
	PACKETNAME_INSERT( UG_TRADE_OK_RES );									// The user's response
	PACKETNAME_INSERT( UG_TRADE_ADD_REQ );                                   // Register item in exchange window 
	PACKETNAME_INSERT( UG_TRADE_DEL_REQ );									// Delete item from exchange window
	PACKETNAME_INSERT( UG_TRADE_MODIFY_REQ );                                   // Change the number of items registered in the exchange window 
	PACKETNAME_INSERT( UG_TRADE_ZENNY_UPDATE_REQ );							// Register and change Zenny in the exchange window
	PACKETNAME_INSERT( UG_TRADE_END_REQ );									// Click the exchange completion button
	PACKETNAME_INSERT( UG_TRADE_CANCEL_REQ );								// Used when canceling an exchange or leaving the character ending distance.
	PACKETNAME_INSERT( UG_TRADE_DENY_REQ );									// Make exchange impossible or possible.
	PACKETNAME_INSERT( UG_GUILD_CREATE_REQ );								// Guild Creation/Disbanding
	PACKETNAME_INSERT( UG_GUILD_INVITE_REQ );								// Inviting to the guild (Guild Member Invitation/Leaving/Kicking Out)
	PACKETNAME_INSERT( UG_TUTORIAL_HINT_UPDATE_REQ );						// Hint Update progress.
	PACKETNAME_INSERT( UG_TUTORIAL_WAIT_CANCEL_REQ );						// Cancel waiting for tutorial
	PACKETNAME_INSERT( UG_TUTORIAL_PLAY_QUIT_REQ );							// Cancel tutorial play

	PACKETNAME_INSERT( UG_RANKBATTLE_INFO_REQ );
	PACKETNAME_INSERT( UG_RANKBATTLE_JOIN_REQ );
	PACKETNAME_INSERT( UG_RANKBATTLE_LEAVE_REQ );
	PACKETNAME_INSERT( UG_DRAGONBALL_CHECK_REQ );							// Dragon Ball UI 7 placement OK
	PACKETNAME_INSERT( UG_DRAGONBALL_REWARD_REQ );							// Request to select a reward for collecting all Dragon Balls
	PACKETNAME_INSERT( UG_PRIVATESHOP_CREATE_REQ );							// Request to create a store [6/28/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_EXIT_REQ );							// Request to close the store completely [6/28/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_OPEN_REQ );							// Request to set store status to Open [6/28/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_CLOSE_REQ );							// Request to change store status to Close [6/28/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_UPDATE_REQ );						// Request to change contents of store items [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_INSERT_REQ );						// Request for additional store items [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_GET_REQ );						// Request store item information
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_DELETE_REQ );						// Request to remove store item [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_BUYING_REQ );						// Request to buy store items [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ENTER_REQ );							// Guest Entry [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_LEAVE_REQ );							// Guest leaving [6/29/2007 SGpro]
	PACKETNAME_INSERT( UG_PRIVATESHOP_ITEM_SELECT_REQ );						// Wishlist [7/19/2007 SGpro]

	PACKETNAME_INSERT( UG_MAIL_START_REQ );
	PACKETNAME_INSERT( UG_MAIL_SEND_REQ );
	PACKETNAME_INSERT( UG_MAIL_READ_REQ );
	PACKETNAME_INSERT( UG_MAIL_DEL_REQ );
	PACKETNAME_INSERT( UG_MAIL_RETURN_REQ );
	PACKETNAME_INSERT( UG_MAIL_RELOAD_REQ );
	PACKETNAME_INSERT( UG_MAIL_LOAD_REQ );
	PACKETNAME_INSERT( UG_MAIL_ITEM_RECEIVE_REQ );
	PACKETNAME_INSERT( UG_MAIL_LOCK_REQ );
	PACKETNAME_INSERT( UG_MAIL_MULTI_DEL_REQ );

	PACKETNAME_INSERT( UG_PORTAL_ADD_REQ );
	PACKETNAME_INSERT( UG_PORTAL_REQ );
	PACKETNAME_INSERT( UG_WAR_FOG_UPDATE_REQ );	
	PACKETNAME_INSERT( UG_GUILD_FUNCTION_ADD_REQ );
	PACKETNAME_INSERT( UG_GUILD_GIVE_ZENNY );
	PACKETNAME_INSERT( UG_GUILD_BANK_START_REQ );							// Loading GUILD Warehouse items
	PACKETNAME_INSERT( UG_GUILD_BANK_MOVE_REQ );							// Moving items in GUILD Warehouse
	PACKETNAME_INSERT( UG_GUILD_BANK_MOVE_STACK_REQ );						// Move stack items in GUILD Warehouse
	PACKETNAME_INSERT( UG_GUILD_BANK_END_REQ );								// Close GUILD Warehouse.
	PACKETNAME_INSERT( UG_GUILD_BANK_ZENNY_REQ );							// Save or withdraw money from GUILD Warehouse.
	PACKETNAME_INSERT( UG_GUILD_CREATE_MARK_REQ );							// GuildMark Create
	PACKETNAME_INSERT( UG_GUILD_CHANGE_MARK_REQ );							// GuildMark Change
	PACKETNAME_INSERT( UG_CROSSFIRE_REQ );
	PACKETNAME_INSERT( UG_BANK_LOAD_REQ );
	PACKETNAME_INSERT( UG_GUILD_CHANGE_NAME_REQ );			
	PACKETNAME_INSERT( UG_PARTY_SHARETARGET_REQ );							// [3/28/2008 SGpro]
	PACKETNAME_INSERT( UG_RIDE_ON_BUS_REQ );
	PACKETNAME_INSERT( UG_RIDE_OFF_BUS_REQ );
	PACKETNAME_INSERT( UG_TRANSFORM_CANCEL_REQ );							// Request to cancel transformation
	PACKETNAME_INSERT( UG_SHOP_ITEM_IDENTIFY_REQ );
	PACKETNAME_INSERT( UG_DICE_ROLL_REQ );									// Action Skill Rolling the Dice
	PACKETNAME_INSERT( UG_BUDOKAI_JOIN_INDIVIDUAL_REQ );						// personal registration
	PACKETNAME_INSERT( UG_BUDOKAI_LEAVE_INDIVIDUAL_REQ );					// personal cancellation
	PACKETNAME_INSERT( UG_BUDOKAI_JOIN_TEAM_INFO_REQ );						//
	PACKETNAME_INSERT( UG_BUDOKAI_JOIN_TEAM_REQ );							// Team Registration
	PACKETNAME_INSERT( UG_BUDOKAI_LEAVE_TEAM_REQ );							// team cancellation
	PACKETNAME_INSERT( UG_BUDOKAI_LEAVE_TEAM_MEMBER_REQ );					// Cancel team member

	PACKETNAME_INSERT( UG_BUDOKAI_JOIN_INFO_REQ );							// Participation Information Request
	PACKETNAME_INSERT( UG_BUDOKAI_JOIN_STATE_REQ );							// Request participation status
	PACKETNAME_INSERT( UG_BUDOKAI_MUDOSA_INFO_REQ );							// Request for martial arts information
	PACKETNAME_INSERT( UG_BUDOKAI_MUDOSA_TELEPORT_REQ );						// Request teleportation to martial arts master
	PACKETNAME_INSERT( UG_BUDOKAI_PARTY_MAKER_REQ );							// Party creation request); For testing of the World's First Martial Arts Club
	PACKETNAME_INSERT( UG_BUDOKAI_SOCIAL_ACTION );

	PACKETNAME_INSERT( UG_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ );				// Request teleportation to World's First Martial Arts Server
	PACKETNAME_INSERT( UG_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_REQ );				// Move from the World's First Martial Arts server to the original server.
	PACKETNAME_INSERT( UG_BUDOKAI_GM_MATCH_PROGRESS_INFO_REQ );				// Request game progress information
	PACKETNAME_INSERT( UG_BUDOKAI_GM_MATCH_ARENA_ENTER_REQ );				// Enter the stadium
	PACKETNAME_INSERT( UG_BUDOKAI_GM_MATCH_ARENA_LEAVE_REQ );				// exit the stadium

	PACKETNAME_INSERT( UG_SCOUTER_TURN_ON );									// scout status on
	PACKETNAME_INSERT( UG_SCOUTER_TURN_OFF );								// Scouter status off
	PACKETNAME_INSERT( UG_SCOUTER_ITEM_SELL_REQ );							// Selling items through scouts

	PACKETNAME_INSERT( UG_SHOP_EVENTITEM_START_REQ );						// [7/15/2008 SGpro]
	PACKETNAME_INSERT( UG_SHOP_EVENTITEM_BUY_REQ );							// [7/11/2008 SGpro]
	PACKETNAME_INSERT( UG_SHOP_EVENTITEM_END_REQ );							// [7/15/2008 SGpro]
	PACKETNAME_INSERT( UG_SHOP_GAMBLE_BUY_REQ );							// [7/11/2008 SGpro]
	PACKETNAME_INSERT( UG_PARTY_DIFF_CHANGE_REQ );							// party dungeon diff change
	PACKETNAME_INSERT( UG_PARTY_DUNGEON_INIT_REQ );							// party dungeon Init
	PACKETNAME_INSERT( UG_SKILL_INIT_REQ );
	PACKETNAME_INSERT( UG_TELEPORT_CONFIRM_REQ );
	PACKETNAME_INSERT( UG_VEHICLE_DIRECT_PLAY_CANCEL_NFY );
	PACKETNAME_INSERT( UG_VEHICLE_END_REQ );								// Stop using vehicles.
	PACKETNAME_INSERT( UG_VEHICLE_STUNT_NFY );							// Press space bar (vehicle)
	PACKETNAME_INSERT( UG_VEHICLE_FUEL_REMOVE_NFY );
	PACKETNAME_INSERT( UG_DOJO_CREATE_REQ );
	PACKETNAME_INSERT( UG_DOJO_DELETE_REQ );
	PACKETNAME_INSERT( UG_DOJO_FUNCTION_ADD_REQ );
	PACKETNAME_INSERT( UG_DOGI_CREATE_REQ );								// Uniform creation
	PACKETNAME_INSERT( UG_DOGI_CHANGE_REQ );								// Uniform change
	PACKETNAME_INSERT( UG_GUILD_DOGI_CREATE_REQ );						// Create Guild Dogi
	PACKETNAME_INSERT( UG_GUILD_DOGI_CHANGE_REQ );						// Guild Dogi change
	PACKETNAME_INSERT( UG_DOJO_SCRAMBLE_REQ );							// Apply for seal competition
	PACKETNAME_INSERT( UG_DOJO_SCRAMBLE_RESPONSE_REQ );					// Response to application for dojo competition
	PACKETNAME_INSERT( UG_SHOP_NETPYITEM_START_REQ );
	PACKETNAME_INSERT( UG_SHOP_NETPYITEM_BUY_REQ );
	PACKETNAME_INSERT( UG_SHOP_NETPYITEM_END_REQ );
	PACKETNAME_INSERT( UG_WORLD_MAP_STATUS );
	PACKETNAME_INSERT( UG_DOJO_NPC_INFO_REQ );							// Request information from Dojo NPC
	PACKETNAME_INSERT( UG_GAMEGUARD_AUTH_ANSWER_RES );
	PACKETNAME_INSERT( UG_GAMEGUARD_HACK_INFO_NFY );
	PACKETNAME_INSERT( UG_SKILL_CASTING_CANCELED_NFY );					// Skill Casting Cancellation Notification
	PACKETNAME_INSERT( UG_PET_ATTACK_TARGET_NFY );						// Pet participation in battle

	PACKETNAME_INSERT( UT_ENTER_CHAT );
	PACKETNAME_INSERT( UT_CHAT_MESSAGE_SAY );
	PACKETNAME_INSERT( UT_CHAT_MESSAGE_SHOUT );
	PACKETNAME_INSERT( UT_CHAT_MESSAGE_WHISPER );
	PACKETNAME_INSERT( UT_CHAT_MESSAGE_PARTY );
	PACKETNAME_INSERT( UT_CHAT_MESSAGE_GUILD );
	PACKETNAME_INSERT( UT_GUILD_DISBAND_REQ );								// Disband the guild
	PACKETNAME_INSERT( UT_GUILD_DISBAND_CANCEL_REQ );						// Cancel guild disbandment
	PACKETNAME_INSERT( UT_GUILD_RESPONSE_INVITATION );						// Send a reply to a guild invitation
	PACKETNAME_INSERT( UT_GUILD_LEAVE_REQ );									// Leave the guild
	PACKETNAME_INSERT( UT_GUILD_KICK_OUT_REQ );								// Force a guild member to withdraw
	PACKETNAME_INSERT( UT_GUILD_APPOINT_SECOND_MASTER_REQ );					// Appoint a guild member as Second Master
	PACKETNAME_INSERT( UT_GUILD_DISMISS_SECOND_MASTER_REQ );					// Remove the position of Guild Second Master
	PACKETNAME_INSERT( UT_GUILD_CHANGE_GUILD_MASTER_REQ );					// Transferring the guild master
	PACKETNAME_INSERT( UT_FRIEND_ADD_REQ );		// add friend
	PACKETNAME_INSERT( UT_FRIEND_DEL_REQ );		// delete friend
	PACKETNAME_INSERT( UT_FRIEND_MOVE_REQ );		// Go to Friends -> Blacklist
	PACKETNAME_INSERT( UT_FRIEND_BLACK_ADD_REQ );		// Add friend blacklist
	PACKETNAME_INSERT( UT_FRIEND_BLACK_DEL_REQ );		// Delete friend blacklist
	PACKETNAME_INSERT( UT_RANKBATTLE_RANK_LIST_REQ );
	PACKETNAME_INSERT( UT_RANKBATTLE_RANK_FIND_CHARACTER_REQ );
	PACKETNAME_INSERT( UT_RANKBATTLE_RANK_COMPARE_DAY_REQ );

	PACKETNAME_INSERT( UT_GUILD_CHANGE_NOTICE_REQ );
	PACKETNAME_INSERT( UT_TMQ_RECORD_LIST_REQ );
	PACKETNAME_INSERT( UT_TMQ_MEMBER_LIST_REQ );
	PACKETNAME_INSERT( UT_BUDOKAI_TOURNAMENT_INDIVIDUAL_LIST_REQ );
	PACKETNAME_INSERT( UT_BUDOKAI_TOURNAMENT_INDIVIDUAL_INFO_REQ );
	PACKETNAME_INSERT( UT_BUDOKAI_TOURNAMENT_TEAM_LIST_REQ );
	PACKETNAME_INSERT( UT_BUDOKAI_TOURNAMENT_TEAM_INFO_REQ );
	PACKETNAME_INSERT( UT_PETITION_CHAT_START_RES );							// [ by sooshia 2008-10-15 ]
	PACKETNAME_INSERT( UT_PETITION_CHAT_USER_SAY_REQ );						// What users said [by sooshia 2008-10-16]
	PACKETNAME_INSERT( UT_PETITION_CHAT_USER_END_NFY );						// [ by sooshia 2008-10-17 ]
	PACKETNAME_INSERT( UT_PETITION_CHAT_GM_SAY_RES );						// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( UT_PETITION_USER_INSERT_REQ );						// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( UT_PETITION_CONTENT_MODIFY_REQ );						// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( UT_PETITION_SATISFACTION_NFY );						// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( UT_PETITION_USER_CANCEL_REQ );						// [ by sooshia 2008-10-18 ]
	PACKETNAME_INSERT( UT_DOJO_BUDOKAI_SEED_ADD_REQ );
	PACKETNAME_INSERT( UT_DOJO_BUDOKAI_SEED_DEL_REQ );
	PACKETNAME_INSERT( UT_DOJO_NOTICE_CHANGE_REQ );
#endif
}